name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        nestjs-version: [9.x, 10.x]
        nestjs-swagger-version: [7.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Remove NestJS packages
        run: npm rm @nestjs/common @nestjs/core @nestjs/swagger
      - name: Install specific NestJS version
        run: npm install @nestjs/common@${{ matrix.nestjs-version }} @nestjs/core@${{ matrix.nestjs-version }} @nestjs/swagger@${{ matrix.nestjs-swagger-version }}
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test